---
title: "Publications"
---

[Google Scholar](https://scholar.google.com/citations?user=5FiapqgAAAAJ&hl=en&oi=ao) \| [ORCID](https://orcid.org/0000-0001-6068-0173)

# Peer-reviewed

**Keller, A.G.** and Kelly, R.P. eDNAjoint: an R package for interpreting paired or semi-paired environmental DNA and traditional survey data in a Bayesian framework. *Methods in Ecology and Evolution*. 00,1–9. [Link](https://doi.org/10.1111/2041-210X.70000) \| [PDF](assets/pubs/Keller_2025b.pdf) \| [Code](https://github.com/ropensci/eDNAjoint) \| [User guide](https://ednajoint.netlify.app/) \| [Webinar](https://www.youtube.com/watch?v=_fBllgza4jU)

**Keller, A.G.**, Counihan, T.D., Grosholz, E.D., Boettiger, C. The transition from resistance to acceptance: managing a marine invasive species in a changing world. (2025). *Journal of Applied Ecology*. [Link](https://doi.org/10.1111/1365-2664.14881) \| [PDF](assets/pubs/Keller_2025a.pdf) \| [Code](https://github.com/abigailkeller/resist-accept)

Goldstein, B.R., **Keller, A.G.**, Calhoun, K.L., Barker, K.J., Montealegre-Mora, F., Serota, M.W., Van Scoyoc, A., Parker-Shames, P., Androzzi, C., de Valpine, P. How do ecologists estimate occupancy in practice? (2024). *Ecography*. [Link](https://doi.org/10.1111/ecog.07402)

Betters, M., Stabbins, A., **Keller, A.G.**, Cordes, E.E. (2023). Biogeography and depth partitioning in deep‐sea gastropods at the Pacific Costa Rica Margin. *Journal of Biogeography*. 50(12), 2109-2121. [Link](https://doi.org/10.1111/jbi.14722) 

Montealegre-Mora, F., Chapman, M., **Keller, A.G.**, Lapeyolerie, M., Boettiger, C. (2023). Pretty darn good control: when are approximate solutions better than approximate models? *Bulletin of Mathematical Biology*. 85, 95. [Link](https://doi.org/10.1007/s11538-023-01198-5)

**Keller, A.G.**, Dahlhoff, E.P., Bracewell, R., Chatla, K., Bachtrog, D., Rank, N.E., Williams, CM. (2023). Multi-locus genomic signatures of local adaptation to snow across the landscape in California populations of the willow leaf beetle. *Proceedings of the Royal Society B: Biological Sciences*. 290(2005). [Link](https://doi.org/10.1098/rspb.2023.0630) \| [PDF](assets/pubs/Keller_2023.pdf)

**Keller, A.G.**, Grason, E. McDonald, P.S., Ramón-Laca, A., Kelly, R.P. (2022). Tracking an invasion front with environmental DNA. *Ecological Applications*. e2561. [Link](https://doi.org/10.1002/eap.2561) \| [PDF](assets/pubs/Keller_2022.pdf) | [Code](https://github.com/abigailkeller/tracking_invasion_front)

Jacobs-Palmer, E., Gallego, R., Cribari, K., **Keller A.G.**, Kelly, R.P. (2021). Environmental DNA Metabarcoding for Simultaneous Monitoring and Ecological Assessment of Many Harmful Algal Bloom Taxa. *Frontiers in Ecology and Evolution*. 9: 612107. [Link](https://doi.org/10.3389/fevo.2021.612107) \| [PDF](assets/pubs/Jacobs-Palmer_2021.pdf)

**Keller, A.G.**, Apprill, A., Lebaron, P., Robbins, J., Romano, T., Overton, E., Yuan, R., Rong, Y., Pollara, S., Whalen, K. (2021). Characterizing the culturable surface microbiomes of diverse marine animals. *FEMS Microbiology Ecology*. 97, fiab040. [Link](https://doi.org/10.1093/femsec/fiab040) \| [PDF](assets/pubs/Keller_2021.pdf)

Goffredi, S.K., Tilic, E., Mullin, S.W., Dawson, K.S., **Keller, A.G.**, Lee, R.W., Wu, F., Levin, L.A., Rouse, G., Cordes, E.E., Orphan, V.J. (2020). Methanotrophic bacterial symbionts fuel dense populations of deep-sea feather duster worms (Sabellida, Annelida) and extend the spatial influence of methane seepage. *Science Advances*. 6: eaay8562. [Link](https://doi.org/10.1126/sciadv.aay8562) \| [PDF](assets/pubs/Goffredi_2020.pdf)

Auscavitch, S.R., Deere, M.C., **Keller, A.G.**, Rotjan, R.D., Shank, T.M., Cordes, E.E. (2020). Oceanographic Drivers of Deep-Sea Coral Species Distribution and Community Assembly on Seamounts, Islands, Atolls, and Reefs Within the Phoenix Islands Protected Area. *Frontiers in Marine Science*. 7:42. [Link](https://doi.org/10.3389/fmars.2020.00042) \| [PDF](assets/pubs/Auscavitch_2020.pdf)

# In review

Acharya-Patel, N., Cram, K., Groenwold, E.T., Lee, H., **Keller, A.G.**, Bomback, B., Lyons, S., Warren, R.L., Coombe, L. Lowe, C., Bergman, L.C., Bishay, F., Birol, I., MacDonald, T.A., Helbing, C.C. Monitoring marine pollution effects through targeted environmental DNA (eDNA) testing in the Pacific Northwest. *Marine Pollution Bulletin*.
